### ISSUE TITLE
Register in table definitions which column is used as fid column

### ISSUE THREAD

**Issue by arbakker** [PDOK/geopackage-validator#107]
Since OGR/GDAL treats the fid column as a special column; it is not included in the feature attributes when outputting a feature with OGR/GDAL. 

So the selection of the fid column impacts the schema of the featuretype, therefore it should be included in the schema definition. Proposal to add a `fid_column` field to the `tables[]` element in the table definitions file like this:

```
geopackage_validator_version: 0.7.0
projection: 3035
tables:
  - name: protected_site_nlps_nnn
    geometry_column: geom
    fid_column: fid
```
